const ENV = {
  NODE_SERVER: process.env.NODE_SERVER,
  SESSION_SECRET: process.env.SESSION_SECRET,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
};

export { ENV };
